version: '3.7'
services:
  service1:
    image: service1
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      SFIA2DB: ${SFIA2DB}
  
  service2:
    image: service2
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp

  service3:
    image: service3
    build: ./service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp


  service4:
    image: service4
    build: ./service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
      SFIA2DB: ${SFIA2DB}

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
