version: '3.7'
services:
  service1:
    image: oskar951/service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      SFIA2DB: ${SFIA2DB}
    deploy:
      replicas: 3
  
  service2:
    image: oskar951/service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 1

  service3:
    image: oskar951/service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 1


  service4:
    image: oskar951/service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
      SFIA2DB: ${SFIA2DB}
    deploy:
      replicas: 3

  nginx_service:
    image: oskar951/nginxservice
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on: 
    - service1
    - service2
    - service3
    - service4
    deploy:
      replicas: 3

    
